services:
  - type: web
    name: mini-event-finder
    env: node
    buildCommand: |
      npm install
      npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /
